INSERT INTO CATEGORIA VALUES(1, 'De luxo'),
INSERT INTO CATEGORIA VALUES(2, 'Muito confortavel'),
INSERT INTO CATEGORIA VALUES(3, 'Confortavel'),
INSERT INTO CATEGORIA VALUES(4, 'Simples'),
INSERT INTO CATEGORIA VALUES(5, 'Sem classificação');